services:
  - type: web
    name: cs-grenade-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free

  - type: static
    name: cs-grenade-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
