services:
  - type: web
    name: cs-grenade-backend
    env: python
    rootDir: backend                 # ✅ 確保這是 app.py 所在的資料夾
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    plan: free
    

  - type: static
    name: cs-grenade-frontend
    rootDir: frontend                # ✅ 確保這是 package.json 所在的資料夾
    buildCommand: npm install && npm run build
    staticPublishPath: dist
